from .auth.routes import auth_blueprint
from .clientes.routes import cliente_blueprint
from .prestamos.routes import prestamo_blueprint
from .roles.routes import role_blueprint
from .usuarios.routes import user_blueprint
from .grupos.routes import grupos_blueprint
from .rutas.routes import rutas_blueprint
from .pagos.routes import pagos_blueprint
from .reporte.routes import reporte_blueprint
from .cortes.routes import cortes_blueprint