from .accion import Accion
from .permiso import Permiso
from .rol import Rol
from .usuario import Usuario
from .prestamo import Prestamo
from .pago import Pago
from .cliente_aval import ClienteAval
from .tipo_prestamo import TipoPrestamo
from .grupo import Grupo
from .ruta import Ruta
from .relationship_tables.roles_permisos import RolesPermisos
